image: docker:latest

variables:
  DOCKERHUB_USER_NAME: $DOCKERHUB_USER_NAME
  DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
  DOCKERREPOSITORY_NAME: citest
  DOCKER_TAG: gitlab

services:
  - docker:dind #Docker in Docker

stages:
  - build

before_script:
  - docker info
  - docker login -u ${DOCKERHUB_USER_NAME} -p ${DOCKERHUB_PASSWORD}

build_job:
  stage: build
  script: 
    - docker build -t ${DOCKERHUB_USER_NAME}/${DOCKERREPOSITORY_NAME}:${DOCKER_TAG} .
    - docker push ${DOCKERHUB_USER_NAME}/${DOCKERREPOSITORY_NAME}:${DOCKER_TAG}
  tags:
    - docker

#after_script:
#  - mvn clean test jacoco:report coveralls:report