version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout

      - run:
        name: build
        command: echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin