# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

#ワークフロー名を「Java CI with Maven」に設定
name: Java CI with Maven 

#masterブランチへのpush時にこのワークフローを実行するよう指定
on:
  push:
    branches: [ master ]

#以下JOB
jobs:
  #ジョブ名(build)を設定
  build:
    #ジョブの実行環境
    runs-on: ubuntu-latest

    #実行する処理やコマンドを指定
    steps:
    - uses: actions/checkout@v2 #リポジトリからのチェックアウトを行う「actions/checkout」アクションを実行する
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2 #「setup-java」コマンドを実行してsetupを行う
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: mvn clean install #「mvn」コマンドを実行してビルドを行う
